[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8"
rmox-fb = { path = "../rmox-fb" }
rmox-input = { path = "../rmox-input" }
time = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
