[package]
name = "rmox-fb"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
embedded-graphics-core = { workspace = true }
libc = "0.2"
memmap2 = "0.9"
rmox-common = { path = "../rmox-common" }
tracing = { workspace = true }
