[package]
name = "rmox-input"
version = "0.1.0"
edition = "2021"

[dependencies]
enumset = "1"
evdev = { version = "0.12", features = ["tokio"] }
futures-core = "0.3"
rmox-common = { path = "../rmox-common" }
tracing = "0.1"
